---
- hosts: redhat_server
  become: true
  tasks:
  - name: Copy html file to centos server
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

