---
- hosts: all
  become: true
  tasks:
  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: update index
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
