---
- hosts: all
  become: true
  tasks:
  - name: install apache2 package
    apt:
      name: apache2                  
      when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    apt:
      name: apache2
      when: ansible_distribution == "Ubuntu"

- hosts: redhat
  become: true
  tasks:
  - name: update index
    yum:
      update_cache: yes

  - name: install apache 2
    yum: 
      name: httpd
      state: latest
