---
- hosts: all
  become: true
  tasks:
    - name: Update Index of Every Remote Server and install two apps
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: true
